<?php

namespace App\Form;

use App\Class\TimeFrom;
use App\Class\TimeTo;
use App\Entity\Reservation;
use App\Entity\Room;
use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserTypePromote extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        //  parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('users', EntityType::class, [
                'attr'=>[
                    'class'=>'col-6'
                ],
                'mapped'=>false,
                'multiple'=>true,
                'class' => User::class,
                'choice_label' => 'firstName',
                'invalid_message' =>'User not valid',
                'query_builder' => function(EntityRepository $er){
                    return $er->createQueryBuilder('u');


                }
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=>User::class]);
    }
}